from flask_restplus import fields
from app.api.restplus import api
from app import settings

# specifications for json request objects

encode_request = api.model('Encode request',{
    'items': fields.List(fields.Raw, required=True,
                        example=[{'fp_id':12334, 'color':'red', 'size':'small'}, {'fp_id':12335, 'color':'blue', 'size':'huge'}],
                        description="""JSON objects to be encoded """,
                        ),
    'fingerprint_id': fields.String(description="""The id that uniquely identifies each object""",
                          default='fp_id', example='fp_id'),
    'L': fields.Integer(description="Length of fingerprint vector", default=10, example=10),
    'normalize':fields.Boolean(description="Whether to normalize the vectors", default=False),
    })

encode_response = api.model('Encode response', {
  'fingerprint_id': fields.String(description="unique_id of fingerprint"),
             'num_triples': fields.Integer(description="Number of triples generated by the input"),
             'fingerprint': fields.List(fields.Float, description="The fingerprint vector"),
             'L': fields.Integer(description="The length of the vector"),
    })
